export const PULL_REQUEST_LIST_REQUEST = 'PULL_REQUEST_LIST_REQUEST'
export const PULL_REQUEST_LIST_SUCCESS = 'PULL_REQUEST_LIST_SUCCESS'
export const PULL_REQUEST_LIST_FAIL = 'PULL_REQUEST_LIST_FAIL'


export const PULL_REQUEST_CREATE_REQUEST = 'PULL_REQUEST_CREATE_REQUEST'
export const PULL_REQUEST_CREATE_SUCCESS = 'PULL_REQUEST_CREATE_SUCCESS'
export const PULL_REQUEST_CREATE_FAIL = 'PULL_REQUEST_CREATE_FAIL'
export const PULL_REQUEST_CREATE_RESET = 'PULL_REQUEST_CREATE_RESET'