export const REPO_DETAIL_REQUEST = 'REPO_DETAIL_REQUEST'
export const REPO_DETAIL_SUCCESS = 'REPO_DETAIL_SUCCESS'
export const REPO_DETAIL_FAIL = 'REPO_DETAIL_FAIL'


export const REPO_BRANCHES_REQUEST = 'REPO_BRANCHES_REQUEST'
export const REPO_BRANCHES_SUCCESS = 'REPO_BRANCHES_SUCCESS'
export const REPO_BRANCHES_FAIL = 'REPO_BRANCHES_FAIL'
